// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/openbank/openbank/v1/consumer/all.proto

package consumer

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateByUser struct {
	UserID               string   `protobuf:"bytes,1,opt,name=UserID,json=user_id,proto3" json:"UserID,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=Email,json=email,proto3" json:"Email,omitempty"`
	ProviderID           string   `protobuf:"bytes,3,opt,name=ProviderID,json=provider_id,proto3" json:"ProviderID,omitempty"`
	Provider             string   `protobuf:"bytes,4,opt,name=Provider,json=provider,proto3" json:"Provider,omitempty"`
	Username             string   `protobuf:"bytes,5,opt,name=Username,json=username,proto3" json:"Username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateByUser) Reset()         { *m = CreateByUser{} }
func (m *CreateByUser) String() string { return proto.CompactTextString(m) }
func (*CreateByUser) ProtoMessage()    {}
func (*CreateByUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_f673d8597f6a7f8e, []int{0}
}

func (m *CreateByUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateByUser.Unmarshal(m, b)
}
func (m *CreateByUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateByUser.Marshal(b, m, deterministic)
}
func (m *CreateByUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateByUser.Merge(m, src)
}
func (m *CreateByUser) XXX_Size() int {
	return xxx_messageInfo_CreateByUser.Size(m)
}
func (m *CreateByUser) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateByUser.DiscardUnknown(m)
}

var xxx_messageInfo_CreateByUser proto.InternalMessageInfo

func (m *CreateByUser) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *CreateByUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateByUser) GetProviderID() string {
	if m != nil {
		return m.ProviderID
	}
	return ""
}

func (m *CreateByUser) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *CreateByUser) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type Consumer struct {
	ID                   int32                `protobuf:"varint,1,opt,name=ID,json=id,proto3" json:"ID,omitempty"`
	AppName              string               `protobuf:"bytes,2,opt,name=AppName,json=app_name,proto3" json:"AppName,omitempty"`
	AppType              string               `protobuf:"bytes,3,opt,name=AppType,json=app_type,proto3" json:"AppType,omitempty"`
	Description          string               `protobuf:"bytes,4,opt,name=Description,json=description,proto3" json:"Description,omitempty"`
	DeveloperEmail       string               `protobuf:"bytes,5,opt,name=DeveloperEmail,json=developer_email,proto3" json:"DeveloperEmail,omitempty"`
	RedirectURL          string               `protobuf:"bytes,6,opt,name=RedirectURL,json=redirect_url,proto3" json:"RedirectURL,omitempty"`
	CreatedByUserID      string               `protobuf:"bytes,7,opt,name=CreatedByUserID,json=created_by_user_id,proto3" json:"CreatedByUserID,omitempty"`
	CreatedByUser        *CreateByUser        `protobuf:"bytes,8,opt,name=CreatedByUser,json=created_by_user,proto3" json:"CreatedByUser,omitempty"`
	Enabled              bool                 `protobuf:"varint,9,opt,name=Enabled,json=enabled,proto3" json:"Enabled,omitempty"`
	Created              *timestamp.Timestamp `protobuf:"bytes,10,opt,name=Created,json=created,proto3" json:"Created,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Consumer) Reset()         { *m = Consumer{} }
func (m *Consumer) String() string { return proto.CompactTextString(m) }
func (*Consumer) ProtoMessage()    {}
func (*Consumer) Descriptor() ([]byte, []int) {
	return fileDescriptor_f673d8597f6a7f8e, []int{1}
}

func (m *Consumer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Consumer.Unmarshal(m, b)
}
func (m *Consumer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Consumer.Marshal(b, m, deterministic)
}
func (m *Consumer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Consumer.Merge(m, src)
}
func (m *Consumer) XXX_Size() int {
	return xxx_messageInfo_Consumer.Size(m)
}
func (m *Consumer) XXX_DiscardUnknown() {
	xxx_messageInfo_Consumer.DiscardUnknown(m)
}

var xxx_messageInfo_Consumer proto.InternalMessageInfo

func (m *Consumer) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Consumer) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *Consumer) GetAppType() string {
	if m != nil {
		return m.AppType
	}
	return ""
}

func (m *Consumer) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Consumer) GetDeveloperEmail() string {
	if m != nil {
		return m.DeveloperEmail
	}
	return ""
}

func (m *Consumer) GetRedirectURL() string {
	if m != nil {
		return m.RedirectURL
	}
	return ""
}

func (m *Consumer) GetCreatedByUserID() string {
	if m != nil {
		return m.CreatedByUserID
	}
	return ""
}

func (m *Consumer) GetCreatedByUser() *CreateByUser {
	if m != nil {
		return m.CreatedByUser
	}
	return nil
}

func (m *Consumer) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *Consumer) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

type EnableOrDisableConsumerRequest struct {
	ConsumerID           string   `protobuf:"bytes,1,opt,name=ConsumerID,json=consumer_id,proto3" json:"ConsumerID,omitempty"`
	Enable               bool     `protobuf:"varint,2,opt,name=Enable,json=enable,proto3" json:"Enable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnableOrDisableConsumerRequest) Reset()         { *m = EnableOrDisableConsumerRequest{} }
func (m *EnableOrDisableConsumerRequest) String() string { return proto.CompactTextString(m) }
func (*EnableOrDisableConsumerRequest) ProtoMessage()    {}
func (*EnableOrDisableConsumerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f673d8597f6a7f8e, []int{2}
}

func (m *EnableOrDisableConsumerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnableOrDisableConsumerRequest.Unmarshal(m, b)
}
func (m *EnableOrDisableConsumerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnableOrDisableConsumerRequest.Marshal(b, m, deterministic)
}
func (m *EnableOrDisableConsumerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnableOrDisableConsumerRequest.Merge(m, src)
}
func (m *EnableOrDisableConsumerRequest) XXX_Size() int {
	return xxx_messageInfo_EnableOrDisableConsumerRequest.Size(m)
}
func (m *EnableOrDisableConsumerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnableOrDisableConsumerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnableOrDisableConsumerRequest proto.InternalMessageInfo

func (m *EnableOrDisableConsumerRequest) GetConsumerID() string {
	if m != nil {
		return m.ConsumerID
	}
	return ""
}

func (m *EnableOrDisableConsumerRequest) GetEnable() bool {
	if m != nil {
		return m.Enable
	}
	return false
}

type EnableOrDisableConsumerResponse struct {
	Enable               bool     `protobuf:"varint,1,opt,name=Enable,json=enable,proto3" json:"Enable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnableOrDisableConsumerResponse) Reset()         { *m = EnableOrDisableConsumerResponse{} }
func (m *EnableOrDisableConsumerResponse) String() string { return proto.CompactTextString(m) }
func (*EnableOrDisableConsumerResponse) ProtoMessage()    {}
func (*EnableOrDisableConsumerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f673d8597f6a7f8e, []int{3}
}

func (m *EnableOrDisableConsumerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnableOrDisableConsumerResponse.Unmarshal(m, b)
}
func (m *EnableOrDisableConsumerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnableOrDisableConsumerResponse.Marshal(b, m, deterministic)
}
func (m *EnableOrDisableConsumerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnableOrDisableConsumerResponse.Merge(m, src)
}
func (m *EnableOrDisableConsumerResponse) XXX_Size() int {
	return xxx_messageInfo_EnableOrDisableConsumerResponse.Size(m)
}
func (m *EnableOrDisableConsumerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EnableOrDisableConsumerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EnableOrDisableConsumerResponse proto.InternalMessageInfo

func (m *EnableOrDisableConsumerResponse) GetEnable() bool {
	if m != nil {
		return m.Enable
	}
	return false
}

type State struct {
	CallsMade            int32    `protobuf:"varint,1,opt,name=CallsMade,json=calls_made,proto3" json:"CallsMade,omitempty"`
	ResetInSeconds       int32    `protobuf:"varint,2,opt,name=ResetInSeconds,json=reset_in_seconds,proto3" json:"ResetInSeconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *State) Reset()         { *m = State{} }
func (m *State) String() string { return proto.CompactTextString(m) }
func (*State) ProtoMessage()    {}
func (*State) Descriptor() ([]byte, []int) {
	return fileDescriptor_f673d8597f6a7f8e, []int{4}
}

func (m *State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_State.Unmarshal(m, b)
}
func (m *State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_State.Marshal(b, m, deterministic)
}
func (m *State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_State.Merge(m, src)
}
func (m *State) XXX_Size() int {
	return xxx_messageInfo_State.Size(m)
}
func (m *State) XXX_DiscardUnknown() {
	xxx_messageInfo_State.DiscardUnknown(m)
}

var xxx_messageInfo_State proto.InternalMessageInfo

func (m *State) GetCallsMade() int32 {
	if m != nil {
		return m.CallsMade
	}
	return 0
}

func (m *State) GetResetInSeconds() int32 {
	if m != nil {
		return m.ResetInSeconds
	}
	return 0
}

type CurrentState struct {
	PerSecond            *State   `protobuf:"bytes,1,opt,name=PerSecond,json=per_second,proto3" json:"PerSecond,omitempty"`
	PerHour              *State   `protobuf:"bytes,2,opt,name=PerHour,json=per_hour,proto3" json:"PerHour,omitempty"`
	PerDay               *State   `protobuf:"bytes,3,opt,name=PerDay,json=per_day,proto3" json:"PerDay,omitempty"`
	PerWeek              *State   `protobuf:"bytes,4,opt,name=PerWeek,json=per_week,proto3" json:"PerWeek,omitempty"`
	PerMonth             *State   `protobuf:"bytes,5,opt,name=PerMonth,json=per_month,proto3" json:"PerMonth,omitempty"`
	PerYear              *State   `protobuf:"bytes,6,opt,name=PerYear,json=per_year,proto3" json:"PerYear,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CurrentState) Reset()         { *m = CurrentState{} }
func (m *CurrentState) String() string { return proto.CompactTextString(m) }
func (*CurrentState) ProtoMessage()    {}
func (*CurrentState) Descriptor() ([]byte, []int) {
	return fileDescriptor_f673d8597f6a7f8e, []int{5}
}

func (m *CurrentState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurrentState.Unmarshal(m, b)
}
func (m *CurrentState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurrentState.Marshal(b, m, deterministic)
}
func (m *CurrentState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrentState.Merge(m, src)
}
func (m *CurrentState) XXX_Size() int {
	return xxx_messageInfo_CurrentState.Size(m)
}
func (m *CurrentState) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrentState.DiscardUnknown(m)
}

var xxx_messageInfo_CurrentState proto.InternalMessageInfo

func (m *CurrentState) GetPerSecond() *State {
	if m != nil {
		return m.PerSecond
	}
	return nil
}

func (m *CurrentState) GetPerHour() *State {
	if m != nil {
		return m.PerHour
	}
	return nil
}

func (m *CurrentState) GetPerDay() *State {
	if m != nil {
		return m.PerDay
	}
	return nil
}

func (m *CurrentState) GetPerWeek() *State {
	if m != nil {
		return m.PerWeek
	}
	return nil
}

func (m *CurrentState) GetPerMonth() *State {
	if m != nil {
		return m.PerMonth
	}
	return nil
}

func (m *CurrentState) GetPerYear() *State {
	if m != nil {
		return m.PerYear
	}
	return nil
}

type GetConsumerCallLimitsRequest struct {
	ConsumerID           string   `protobuf:"bytes,1,opt,name=ConsumerID,json=consumer_id,proto3" json:"ConsumerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConsumerCallLimitsRequest) Reset()         { *m = GetConsumerCallLimitsRequest{} }
func (m *GetConsumerCallLimitsRequest) String() string { return proto.CompactTextString(m) }
func (*GetConsumerCallLimitsRequest) ProtoMessage()    {}
func (*GetConsumerCallLimitsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f673d8597f6a7f8e, []int{6}
}

func (m *GetConsumerCallLimitsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConsumerCallLimitsRequest.Unmarshal(m, b)
}
func (m *GetConsumerCallLimitsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConsumerCallLimitsRequest.Marshal(b, m, deterministic)
}
func (m *GetConsumerCallLimitsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConsumerCallLimitsRequest.Merge(m, src)
}
func (m *GetConsumerCallLimitsRequest) XXX_Size() int {
	return xxx_messageInfo_GetConsumerCallLimitsRequest.Size(m)
}
func (m *GetConsumerCallLimitsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConsumerCallLimitsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetConsumerCallLimitsRequest proto.InternalMessageInfo

func (m *GetConsumerCallLimitsRequest) GetConsumerID() string {
	if m != nil {
		return m.ConsumerID
	}
	return ""
}

type GetConsumerCallLimitsResponse struct {
	PerSecondCallLimit   string        `protobuf:"bytes,1,opt,name=PerSecondCallLimit,json=per_second_call_limit,proto3" json:"PerSecondCallLimit,omitempty"`
	PerMinuteCallLimit   string        `protobuf:"bytes,2,opt,name=PerMinuteCallLimit,json=per_minute_call_limit,proto3" json:"PerMinuteCallLimit,omitempty"`
	PerHourCallLimit     string        `protobuf:"bytes,3,opt,name=PerHourCallLimit,json=per_hour_call_limit,proto3" json:"PerHourCallLimit,omitempty"`
	PerDayCallLimit      string        `protobuf:"bytes,4,opt,name=PerDayCallLimit,json=per_day_call_limit,proto3" json:"PerDayCallLimit,omitempty"`
	PerWeekCallLimit     string        `protobuf:"bytes,5,opt,name=PerWeekCallLimit,json=per_week_call_limit,proto3" json:"PerWeekCallLimit,omitempty"`
	PerMonthCallLimit    string        `protobuf:"bytes,6,opt,name=PerMonthCallLimit,json=per_month_call_limit,proto3" json:"PerMonthCallLimit,omitempty"`
	CurrentState         *CurrentState `protobuf:"bytes,7,opt,name=CurrentState,json=current_state,proto3" json:"CurrentState,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetConsumerCallLimitsResponse) Reset()         { *m = GetConsumerCallLimitsResponse{} }
func (m *GetConsumerCallLimitsResponse) String() string { return proto.CompactTextString(m) }
func (*GetConsumerCallLimitsResponse) ProtoMessage()    {}
func (*GetConsumerCallLimitsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f673d8597f6a7f8e, []int{7}
}

func (m *GetConsumerCallLimitsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConsumerCallLimitsResponse.Unmarshal(m, b)
}
func (m *GetConsumerCallLimitsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConsumerCallLimitsResponse.Marshal(b, m, deterministic)
}
func (m *GetConsumerCallLimitsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConsumerCallLimitsResponse.Merge(m, src)
}
func (m *GetConsumerCallLimitsResponse) XXX_Size() int {
	return xxx_messageInfo_GetConsumerCallLimitsResponse.Size(m)
}
func (m *GetConsumerCallLimitsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConsumerCallLimitsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetConsumerCallLimitsResponse proto.InternalMessageInfo

func (m *GetConsumerCallLimitsResponse) GetPerSecondCallLimit() string {
	if m != nil {
		return m.PerSecondCallLimit
	}
	return ""
}

func (m *GetConsumerCallLimitsResponse) GetPerMinuteCallLimit() string {
	if m != nil {
		return m.PerMinuteCallLimit
	}
	return ""
}

func (m *GetConsumerCallLimitsResponse) GetPerHourCallLimit() string {
	if m != nil {
		return m.PerHourCallLimit
	}
	return ""
}

func (m *GetConsumerCallLimitsResponse) GetPerDayCallLimit() string {
	if m != nil {
		return m.PerDayCallLimit
	}
	return ""
}

func (m *GetConsumerCallLimitsResponse) GetPerWeekCallLimit() string {
	if m != nil {
		return m.PerWeekCallLimit
	}
	return ""
}

func (m *GetConsumerCallLimitsResponse) GetPerMonthCallLimit() string {
	if m != nil {
		return m.PerMonthCallLimit
	}
	return ""
}

func (m *GetConsumerCallLimitsResponse) GetCurrentState() *CurrentState {
	if m != nil {
		return m.CurrentState
	}
	return nil
}

type GetConsumerRequest struct {
	ConsumerID           string   `protobuf:"bytes,1,opt,name=ConsumerID,json=consumer_id,proto3" json:"ConsumerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConsumerRequest) Reset()         { *m = GetConsumerRequest{} }
func (m *GetConsumerRequest) String() string { return proto.CompactTextString(m) }
func (*GetConsumerRequest) ProtoMessage()    {}
func (*GetConsumerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f673d8597f6a7f8e, []int{8}
}

func (m *GetConsumerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConsumerRequest.Unmarshal(m, b)
}
func (m *GetConsumerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConsumerRequest.Marshal(b, m, deterministic)
}
func (m *GetConsumerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConsumerRequest.Merge(m, src)
}
func (m *GetConsumerRequest) XXX_Size() int {
	return xxx_messageInfo_GetConsumerRequest.Size(m)
}
func (m *GetConsumerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConsumerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetConsumerRequest proto.InternalMessageInfo

func (m *GetConsumerRequest) GetConsumerID() string {
	if m != nil {
		return m.ConsumerID
	}
	return ""
}

type GetConsumerResponse struct {
	Consumer             *Consumer `protobuf:"bytes,1,opt,name=Consumer,json=consumer,proto3" json:"Consumer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetConsumerResponse) Reset()         { *m = GetConsumerResponse{} }
func (m *GetConsumerResponse) String() string { return proto.CompactTextString(m) }
func (*GetConsumerResponse) ProtoMessage()    {}
func (*GetConsumerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f673d8597f6a7f8e, []int{9}
}

func (m *GetConsumerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConsumerResponse.Unmarshal(m, b)
}
func (m *GetConsumerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConsumerResponse.Marshal(b, m, deterministic)
}
func (m *GetConsumerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConsumerResponse.Merge(m, src)
}
func (m *GetConsumerResponse) XXX_Size() int {
	return xxx_messageInfo_GetConsumerResponse.Size(m)
}
func (m *GetConsumerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConsumerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetConsumerResponse proto.InternalMessageInfo

func (m *GetConsumerResponse) GetConsumer() *Consumer {
	if m != nil {
		return m.Consumer
	}
	return nil
}

type GetConsumersResponse struct {
	Consumers            []*Consumer `protobuf:"bytes,1,rep,name=Consumers,json=consumers,proto3" json:"Consumers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetConsumersResponse) Reset()         { *m = GetConsumersResponse{} }
func (m *GetConsumersResponse) String() string { return proto.CompactTextString(m) }
func (*GetConsumersResponse) ProtoMessage()    {}
func (*GetConsumersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f673d8597f6a7f8e, []int{10}
}

func (m *GetConsumersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConsumersResponse.Unmarshal(m, b)
}
func (m *GetConsumersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConsumersResponse.Marshal(b, m, deterministic)
}
func (m *GetConsumersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConsumersResponse.Merge(m, src)
}
func (m *GetConsumersResponse) XXX_Size() int {
	return xxx_messageInfo_GetConsumersResponse.Size(m)
}
func (m *GetConsumersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConsumersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetConsumersResponse proto.InternalMessageInfo

func (m *GetConsumersResponse) GetConsumers() []*Consumer {
	if m != nil {
		return m.Consumers
	}
	return nil
}

type GetConsumersForLoggedInUserResponse struct {
	Consumers            []*Consumer `protobuf:"bytes,1,rep,name=Consumers,json=consumers,proto3" json:"Consumers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetConsumersForLoggedInUserResponse) Reset()         { *m = GetConsumersForLoggedInUserResponse{} }
func (m *GetConsumersForLoggedInUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetConsumersForLoggedInUserResponse) ProtoMessage()    {}
func (*GetConsumersForLoggedInUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f673d8597f6a7f8e, []int{11}
}

func (m *GetConsumersForLoggedInUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConsumersForLoggedInUserResponse.Unmarshal(m, b)
}
func (m *GetConsumersForLoggedInUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConsumersForLoggedInUserResponse.Marshal(b, m, deterministic)
}
func (m *GetConsumersForLoggedInUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConsumersForLoggedInUserResponse.Merge(m, src)
}
func (m *GetConsumersForLoggedInUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetConsumersForLoggedInUserResponse.Size(m)
}
func (m *GetConsumersForLoggedInUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConsumersForLoggedInUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetConsumersForLoggedInUserResponse proto.InternalMessageInfo

func (m *GetConsumersForLoggedInUserResponse) GetConsumers() []*Consumer {
	if m != nil {
		return m.Consumers
	}
	return nil
}

type SetConsumerCallsLimitRequest struct {
	ConsumerID           string   `protobuf:"bytes,1,opt,name=ConsumerID,json=consumer_id,proto3" json:"ConsumerID,omitempty"`
	PerSecondCallLimit   string   `protobuf:"bytes,2,opt,name=PerSecondCallLimit,json=per_second_call_limit,proto3" json:"PerSecondCallLimit,omitempty"`
	PerMinuteCallLimit   string   `protobuf:"bytes,3,opt,name=PerMinuteCallLimit,json=per_minute_call_limit,proto3" json:"PerMinuteCallLimit,omitempty"`
	PerHourCallLimit     string   `protobuf:"bytes,4,opt,name=PerHourCallLimit,json=per_hour_call_limit,proto3" json:"PerHourCallLimit,omitempty"`
	PerDayCallLimit      string   `protobuf:"bytes,5,opt,name=PerDayCallLimit,json=per_day_call_limit,proto3" json:"PerDayCallLimit,omitempty"`
	PerWeekCallLimit     string   `protobuf:"bytes,6,opt,name=PerWeekCallLimit,json=per_week_call_limit,proto3" json:"PerWeekCallLimit,omitempty"`
	PerMonthCallLimit    string   `protobuf:"bytes,7,opt,name=PerMonthCallLimit,json=per_month_call_limit,proto3" json:"PerMonthCallLimit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetConsumerCallsLimitRequest) Reset()         { *m = SetConsumerCallsLimitRequest{} }
func (m *SetConsumerCallsLimitRequest) String() string { return proto.CompactTextString(m) }
func (*SetConsumerCallsLimitRequest) ProtoMessage()    {}
func (*SetConsumerCallsLimitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f673d8597f6a7f8e, []int{12}
}

func (m *SetConsumerCallsLimitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConsumerCallsLimitRequest.Unmarshal(m, b)
}
func (m *SetConsumerCallsLimitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConsumerCallsLimitRequest.Marshal(b, m, deterministic)
}
func (m *SetConsumerCallsLimitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConsumerCallsLimitRequest.Merge(m, src)
}
func (m *SetConsumerCallsLimitRequest) XXX_Size() int {
	return xxx_messageInfo_SetConsumerCallsLimitRequest.Size(m)
}
func (m *SetConsumerCallsLimitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConsumerCallsLimitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetConsumerCallsLimitRequest proto.InternalMessageInfo

func (m *SetConsumerCallsLimitRequest) GetConsumerID() string {
	if m != nil {
		return m.ConsumerID
	}
	return ""
}

func (m *SetConsumerCallsLimitRequest) GetPerSecondCallLimit() string {
	if m != nil {
		return m.PerSecondCallLimit
	}
	return ""
}

func (m *SetConsumerCallsLimitRequest) GetPerMinuteCallLimit() string {
	if m != nil {
		return m.PerMinuteCallLimit
	}
	return ""
}

func (m *SetConsumerCallsLimitRequest) GetPerHourCallLimit() string {
	if m != nil {
		return m.PerHourCallLimit
	}
	return ""
}

func (m *SetConsumerCallsLimitRequest) GetPerDayCallLimit() string {
	if m != nil {
		return m.PerDayCallLimit
	}
	return ""
}

func (m *SetConsumerCallsLimitRequest) GetPerWeekCallLimit() string {
	if m != nil {
		return m.PerWeekCallLimit
	}
	return ""
}

func (m *SetConsumerCallsLimitRequest) GetPerMonthCallLimit() string {
	if m != nil {
		return m.PerMonthCallLimit
	}
	return ""
}

type SetConsumerCallsLimitResponse struct {
	PerSecondCallLimit   string   `protobuf:"bytes,1,opt,name=PerSecondCallLimit,json=per_second_call_limit,proto3" json:"PerSecondCallLimit,omitempty"`
	PerMinuteCallLimit   string   `protobuf:"bytes,2,opt,name=PerMinuteCallLimit,json=per_minute_call_limit,proto3" json:"PerMinuteCallLimit,omitempty"`
	PerHourCallLimit     string   `protobuf:"bytes,3,opt,name=PerHourCallLimit,json=per_hour_call_limit,proto3" json:"PerHourCallLimit,omitempty"`
	PerDayCallLimit      string   `protobuf:"bytes,4,opt,name=PerDayCallLimit,json=per_day_call_limit,proto3" json:"PerDayCallLimit,omitempty"`
	PerWeekCallLimit     string   `protobuf:"bytes,5,opt,name=PerWeekCallLimit,json=per_week_call_limit,proto3" json:"PerWeekCallLimit,omitempty"`
	PerMonthCallLimit    string   `protobuf:"bytes,6,opt,name=PerMonthCallLimit,json=per_month_call_limit,proto3" json:"PerMonthCallLimit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetConsumerCallsLimitResponse) Reset()         { *m = SetConsumerCallsLimitResponse{} }
func (m *SetConsumerCallsLimitResponse) String() string { return proto.CompactTextString(m) }
func (*SetConsumerCallsLimitResponse) ProtoMessage()    {}
func (*SetConsumerCallsLimitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f673d8597f6a7f8e, []int{13}
}

func (m *SetConsumerCallsLimitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConsumerCallsLimitResponse.Unmarshal(m, b)
}
func (m *SetConsumerCallsLimitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConsumerCallsLimitResponse.Marshal(b, m, deterministic)
}
func (m *SetConsumerCallsLimitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConsumerCallsLimitResponse.Merge(m, src)
}
func (m *SetConsumerCallsLimitResponse) XXX_Size() int {
	return xxx_messageInfo_SetConsumerCallsLimitResponse.Size(m)
}
func (m *SetConsumerCallsLimitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConsumerCallsLimitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetConsumerCallsLimitResponse proto.InternalMessageInfo

func (m *SetConsumerCallsLimitResponse) GetPerSecondCallLimit() string {
	if m != nil {
		return m.PerSecondCallLimit
	}
	return ""
}

func (m *SetConsumerCallsLimitResponse) GetPerMinuteCallLimit() string {
	if m != nil {
		return m.PerMinuteCallLimit
	}
	return ""
}

func (m *SetConsumerCallsLimitResponse) GetPerHourCallLimit() string {
	if m != nil {
		return m.PerHourCallLimit
	}
	return ""
}

func (m *SetConsumerCallsLimitResponse) GetPerDayCallLimit() string {
	if m != nil {
		return m.PerDayCallLimit
	}
	return ""
}

func (m *SetConsumerCallsLimitResponse) GetPerWeekCallLimit() string {
	if m != nil {
		return m.PerWeekCallLimit
	}
	return ""
}

func (m *SetConsumerCallsLimitResponse) GetPerMonthCallLimit() string {
	if m != nil {
		return m.PerMonthCallLimit
	}
	return ""
}

type UpdateConsumerRedirectURLRequest struct {
	ConsumerID           string   `protobuf:"bytes,1,opt,name=ConsumerID,json=consumer_id,proto3" json:"ConsumerID,omitempty"`
	RedirectURL          string   `protobuf:"bytes,2,opt,name=RedirectURL,json=redirect_url,proto3" json:"RedirectURL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateConsumerRedirectURLRequest) Reset()         { *m = UpdateConsumerRedirectURLRequest{} }
func (m *UpdateConsumerRedirectURLRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateConsumerRedirectURLRequest) ProtoMessage()    {}
func (*UpdateConsumerRedirectURLRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f673d8597f6a7f8e, []int{14}
}

func (m *UpdateConsumerRedirectURLRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateConsumerRedirectURLRequest.Unmarshal(m, b)
}
func (m *UpdateConsumerRedirectURLRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateConsumerRedirectURLRequest.Marshal(b, m, deterministic)
}
func (m *UpdateConsumerRedirectURLRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateConsumerRedirectURLRequest.Merge(m, src)
}
func (m *UpdateConsumerRedirectURLRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateConsumerRedirectURLRequest.Size(m)
}
func (m *UpdateConsumerRedirectURLRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateConsumerRedirectURLRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateConsumerRedirectURLRequest proto.InternalMessageInfo

func (m *UpdateConsumerRedirectURLRequest) GetConsumerID() string {
	if m != nil {
		return m.ConsumerID
	}
	return ""
}

func (m *UpdateConsumerRedirectURLRequest) GetRedirectURL() string {
	if m != nil {
		return m.RedirectURL
	}
	return ""
}

type UpdateConsumerRedirectURLResponse struct {
	Consumer             *Consumer `protobuf:"bytes,1,opt,name=Consumer,json=consumer,proto3" json:"Consumer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateConsumerRedirectURLResponse) Reset()         { *m = UpdateConsumerRedirectURLResponse{} }
func (m *UpdateConsumerRedirectURLResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateConsumerRedirectURLResponse) ProtoMessage()    {}
func (*UpdateConsumerRedirectURLResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f673d8597f6a7f8e, []int{15}
}

func (m *UpdateConsumerRedirectURLResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateConsumerRedirectURLResponse.Unmarshal(m, b)
}
func (m *UpdateConsumerRedirectURLResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateConsumerRedirectURLResponse.Marshal(b, m, deterministic)
}
func (m *UpdateConsumerRedirectURLResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateConsumerRedirectURLResponse.Merge(m, src)
}
func (m *UpdateConsumerRedirectURLResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateConsumerRedirectURLResponse.Size(m)
}
func (m *UpdateConsumerRedirectURLResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateConsumerRedirectURLResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateConsumerRedirectURLResponse proto.InternalMessageInfo

func (m *UpdateConsumerRedirectURLResponse) GetConsumer() *Consumer {
	if m != nil {
		return m.Consumer
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateByUser)(nil), "consumer.CreateByUser")
	proto.RegisterType((*Consumer)(nil), "consumer.Consumer")
	proto.RegisterType((*EnableOrDisableConsumerRequest)(nil), "consumer.EnableOrDisableConsumerRequest")
	proto.RegisterType((*EnableOrDisableConsumerResponse)(nil), "consumer.EnableOrDisableConsumerResponse")
	proto.RegisterType((*State)(nil), "consumer.State")
	proto.RegisterType((*CurrentState)(nil), "consumer.CurrentState")
	proto.RegisterType((*GetConsumerCallLimitsRequest)(nil), "consumer.GetConsumerCallLimitsRequest")
	proto.RegisterType((*GetConsumerCallLimitsResponse)(nil), "consumer.GetConsumerCallLimitsResponse")
	proto.RegisterType((*GetConsumerRequest)(nil), "consumer.GetConsumerRequest")
	proto.RegisterType((*GetConsumerResponse)(nil), "consumer.GetConsumerResponse")
	proto.RegisterType((*GetConsumersResponse)(nil), "consumer.GetConsumersResponse")
	proto.RegisterType((*GetConsumersForLoggedInUserResponse)(nil), "consumer.GetConsumersForLoggedInUserResponse")
	proto.RegisterType((*SetConsumerCallsLimitRequest)(nil), "consumer.SetConsumerCallsLimitRequest")
	proto.RegisterType((*SetConsumerCallsLimitResponse)(nil), "consumer.SetConsumerCallsLimitResponse")
	proto.RegisterType((*UpdateConsumerRedirectURLRequest)(nil), "consumer.UpdateConsumerRedirectURLRequest")
	proto.RegisterType((*UpdateConsumerRedirectURLResponse)(nil), "consumer.UpdateConsumerRedirectURLResponse")
}

func init() {
	proto.RegisterFile("github.com/openbank/openbank/v1/consumer/all.proto", fileDescriptor_f673d8597f6a7f8e)
}

var fileDescriptor_f673d8597f6a7f8e = []byte{
	// 2083 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x59, 0x4d, 0x6f, 0x1b, 0xc7,
	0x19, 0xe6, 0x92, 0xa6, 0x44, 0x8d, 0xec, 0xd8, 0x19, 0xc7, 0x09, 0xb3, 0xf1, 0xc7, 0x54, 0x6e,
	0x6c, 0x59, 0xb6, 0x96, 0x34, 0xed, 0xc4, 0xb1, 0x1c, 0x23, 0xa1, 0x25, 0xdb, 0x91, 0x60, 0xd7,
	0x82, 0x64, 0x27, 0x75, 0x90, 0x82, 0x1d, 0xed, 0xbe, 0x92, 0xb6, 0x5e, 0xee, 0x6c, 0x67, 0x66,
	0xa5, 0xb0, 0x45, 0x81, 0xa2, 0x87, 0xc0, 0xc7, 0x44, 0x3d, 0xf5, 0x0f, 0xb4, 0x39, 0x14, 0x45,
	0x91, 0x53, 0x8b, 0xa0, 0x40, 0xff, 0x40, 0x81, 0x02, 0xbd, 0xb4, 0x01, 0xda, 0x53, 0x7b, 0x68,
	0xd0, 0x43, 0x8f, 0x01, 0x7a, 0x29, 0x66, 0x67, 0xbf, 0x68, 0x2e, 0x45, 0xc5, 0x16, 0x7a, 0xea,
	0x49, 0xf4, 0xbe, 0x9f, 0xf3, 0x3c, 0xcf, 0x3b, 0xfb, 0x92, 0x46, 0xad, 0x0d, 0x57, 0x6e, 0x86,
	0x6b, 0x96, 0xcd, 0xba, 0x0d, 0x16, 0x80, 0xbf, 0x46, 0xfd, 0x47, 0xd9, 0x87, 0xad, 0x8b, 0x0d,
	0x9b, 0xf9, 0x22, 0xec, 0x02, 0x6f, 0x50, 0xcf, 0xb3, 0x02, 0xce, 0x24, 0xc3, 0xb5, 0xe4, 0x99,
	0x79, 0x6a, 0x83, 0xb1, 0x0d, 0x0f, 0x1a, 0xd1, 0xf3, 0xb5, 0x70, 0xbd, 0x21, 0xdd, 0x2e, 0x08,
	0x49, 0xbb, 0x81, 0x76, 0x35, 0x8f, 0xc7, 0x0e, 0x34, 0x70, 0x1b, 0xd4, 0xf7, 0x99, 0xa4, 0xd2,
	0x65, 0xbe, 0x88, 0xad, 0x17, 0xa2, 0x3f, 0xf6, 0xec, 0x06, 0xf8, 0xb3, 0x62, 0x9b, 0x6e, 0x6c,
	0x00, 0x6f, 0xb0, 0x20, 0xf2, 0x28, 0xf0, 0x7e, 0xe5, 0xc9, 0x62, 0xd0, 0x0d, 0x64, 0x4f, 0x1b,
	0xa7, 0xbe, 0x30, 0xd0, 0xc1, 0x79, 0x0e, 0x54, 0xc2, 0x8d, 0xde, 0x03, 0x01, 0x1c, 0x9f, 0x46,
	0x63, 0xea, 0xef, 0xe2, 0x42, 0xdd, 0x20, 0xc6, 0xf4, 0xc4, 0x0d, 0x54, 0x2b, 0xd5, 0x4b, 0xd3,
	0xa5, 0x66, 0x69, 0xb9, 0xb4, 0x32, 0x1e, 0x0a, 0xe0, 0x1d, 0xd7, 0xc1, 0x04, 0x55, 0x6f, 0x76,
	0xa9, 0xeb, 0xd5, 0xcb, 0x03, 0x3e, 0x55, 0x50, 0x06, 0x7c, 0x1e, 0xa1, 0x65, 0xce, 0xb6, 0x5c,
	0x27, 0x4a, 0x55, 0x19, 0x70, 0x9b, 0x0c, 0x62, 0xab, 0x4a, 0x77, 0x06, 0xd5, 0x12, 0xe7, 0xfa,
	0x81, 0x01, 0xd7, 0x5a, 0xe2, 0xaa, 0xfc, 0x54, 0x6f, 0x3e, 0xed, 0x42, 0xbd, 0x3a, 0xe8, 0x17,
	0xc6, 0xb6, 0xb9, 0xb1, 0x5a, 0xe9, 0x48, 0xa9, 0x5e, 0x9a, 0xfa, 0x4f, 0x05, 0xd5, 0xe6, 0x63,
	0xcc, 0xb1, 0x89, 0xca, 0xf1, 0xa1, 0xaa, 0x7d, 0x61, 0x65, 0xd7, 0xc1, 0xaf, 0xa2, 0xf1, 0x76,
	0x10, 0x7c, 0x4b, 0xe5, 0x1d, 0x3c, 0x51, 0x8d, 0x06, 0x41, 0x47, 0xe5, 0x8d, 0xdd, 0xee, 0xf7,
	0x02, 0x28, 0x38, 0x51, 0xe4, 0x26, 0x7b, 0x01, 0xe0, 0x0b, 0x68, 0x72, 0x01, 0x84, 0xcd, 0xdd,
	0x88, 0x92, 0x82, 0x13, 0x4d, 0x3a, 0x99, 0x19, 0x5f, 0x42, 0xcf, 0x2d, 0xc0, 0x16, 0x78, 0x2c,
	0x00, 0xae, 0x41, 0x1d, 0x3c, 0xda, 0x61, 0x27, 0xf1, 0xe8, 0x68, 0x78, 0x67, 0xd1, 0xe4, 0x0a,
	0x38, 0x2e, 0x07, 0x5b, 0x3e, 0x58, 0xb9, 0x53, 0x1f, 0x1b, 0x88, 0x38, 0xc8, 0x63, 0x73, 0x27,
	0xe4, 0x1e, 0xbe, 0x82, 0x0e, 0x6b, 0x92, 0x1d, 0xcd, 0xf2, 0xe2, 0x42, 0x7d, 0x7c, 0x20, 0x04,
	0xdb, 0xda, 0xa5, 0xb3, 0xd6, 0xeb, 0x24, 0x44, 0x2f, 0xa1, 0x43, 0x7d, 0x81, 0xf5, 0x1a, 0x31,
	0xa6, 0x27, 0x5b, 0x2f, 0x5a, 0x89, 0x94, 0xad, 0xbc, 0x78, 0xfa, 0x7b, 0x7e, 0x22, 0x1d, 0xfe,
	0x26, 0x1a, 0xbf, 0xe9, 0xd3, 0x35, 0x0f, 0x9c, 0xfa, 0x04, 0x31, 0xa6, 0x6b, 0xfd, 0xd2, 0x02,
	0x6d, 0xc2, 0x6f, 0xa3, 0xf1, 0xb8, 0x62, 0x1d, 0x45, 0xb5, 0x4c, 0x4b, 0xeb, 0xd7, 0x4a, 0xf4,
	0x6b, 0xdd, 0x4f, 0x86, 0xa5, 0x3f, 0x43, 0x5c, 0x2f, 0x65, 0xbf, 0x87, 0x4e, 0xea, 0x7a, 0xf7,
	0xf8, 0x82, 0x2b, 0xd4, 0x87, 0x44, 0x0b, 0x2b, 0xf0, 0xfd, 0x10, 0x84, 0x54, 0x22, 0x4d, 0x1e,
	0x15, 0xea, 0x7d, 0x32, 0x39, 0xa5, 0x82, 0x62, 0x0a, 0x8d, 0xe9, 0x74, 0x91, 0x44, 0xfa, 0xbb,
	0x1f, 0xd3, 0xdd, 0xa7, 0xa5, 0xef, 0xa2, 0x53, 0x43, 0x4b, 0x8b, 0x80, 0xf9, 0x02, 0x72, 0xe9,
	0x8c, 0x91, 0xe9, 0x02, 0x54, 0x5d, 0x95, 0x54, 0x02, 0x3e, 0x87, 0x26, 0xe6, 0xa9, 0xe7, 0x89,
	0xbb, 0xd4, 0x81, 0x02, 0x29, 0x23, 0x5b, 0x19, 0x3b, 0x5d, 0xea, 0x00, 0xbe, 0x8c, 0x9e, 0x5b,
	0x01, 0x01, 0x72, 0xd1, 0x5f, 0x05, 0x9b, 0xf9, 0x8e, 0x88, 0xda, 0xee, 0xf7, 0x3f, 0xc2, 0x95,
	0x47, 0xc7, 0xf5, 0x3b, 0x42, 0xfb, 0xa4, 0x15, 0xbf, 0x2c, 0xa3, 0x83, 0xf3, 0x21, 0xe7, 0xe0,
	0x4b, 0x5d, 0x79, 0x0e, 0x4d, 0x2c, 0x03, 0xd7, 0xa9, 0xa2, 0xca, 0x93, 0xad, 0xc3, 0x99, 0x08,
	0x22, 0x9f, 0xfe, 0x56, 0x94, 0x56, 0x75, 0x56, 0xfc, 0x3a, 0x1a, 0x5f, 0x06, 0xfe, 0x0e, 0x0b,
	0x79, 0xd4, 0xc3, 0x88, 0xc8, 0x9a, 0x8a, 0xdc, 0x64, 0x21, 0xc7, 0x97, 0xd1, 0xd8, 0x32, 0xf0,
	0x05, 0xda, 0x8b, 0xa6, 0x6d, 0x44, 0xd8, 0xb8, 0x0a, 0x73, 0x68, 0x2f, 0xae, 0xf6, 0x1e, 0xc0,
	0xa3, 0x68, 0xf2, 0xf6, 0x52, 0x6d, 0x1b, 0xe0, 0x11, 0x7e, 0x03, 0xd5, 0x96, 0x81, 0xdf, 0x65,
	0xbe, 0xdc, 0x8c, 0x26, 0x70, 0x44, 0xe0, 0x84, 0x0a, 0xec, 0x2a, 0xef, 0xb8, 0xe2, 0x43, 0xa0,
	0x3c, 0x1a, 0xc4, 0xbd, 0x54, 0xec, 0x01, 0xe5, 0x29, 0xd8, 0xab, 0xe8, 0xf8, 0x6d, 0x90, 0x89,
	0x42, 0x14, 0xc1, 0x77, 0xdc, 0xae, 0x2b, 0xc5, 0xd3, 0xc8, 0x34, 0x4d, 0xfa, 0x45, 0x05, 0x9d,
	0x18, 0x92, 0x35, 0x56, 0xe0, 0x75, 0x84, 0x53, 0x4a, 0x53, 0x73, 0x41, 0xfa, 0x63, 0x19, 0x95,
	0x1d, 0x25, 0xb0, 0x8e, 0xa7, 0x1c, 0xe3, 0xf0, 0xbb, 0xae, 0x1f, 0x4a, 0xc8, 0xc2, 0xcb, 0xc5,
	0xe1, 0xdd, 0xc8, 0x2d, 0x1f, 0x7e, 0x15, 0x1d, 0x89, 0x45, 0x91, 0x05, 0x0f, 0x5e, 0xaa, 0x47,
	0x13, 0x31, 0xe4, 0x43, 0xaf, 0xa0, 0xc3, 0x5a, 0x17, 0x59, 0xe4, 0xe0, 0x1d, 0x8b, 0x63, 0x3d,
	0x0c, 0xd6, 0x54, 0xd2, 0xc8, 0x22, 0xab, 0xc5, 0x35, 0x95, 0x24, 0xf2, 0xa1, 0xd7, 0xd0, 0xf3,
	0x89, 0x3a, 0xb2, 0xd8, 0xc1, 0x6b, 0xf7, 0x85, 0x54, 0x15, 0xf9, 0xe0, 0xdb, 0xfd, 0xc3, 0x14,
	0xdd, 0xbd, 0xfd, 0x97, 0x68, 0xce, 0xda, 0x97, 0xef, 0x90, 0xad, 0x2d, 0x1d, 0xa1, 0x4c, 0x29,
	0xb9, 0x8b, 0x08, 0xe7, 0xb8, 0x7d, 0x26, 0x9d, 0x3c, 0x44, 0x47, 0xfb, 0x52, 0xc5, 0xe2, 0x98,
	0xcb, 0xde, 0x9c, 0xf1, 0xb8, 0xe3, 0x5c, 0xbb, 0xf1, 0x87, 0x7e, 0x5d, 0x27, 0xe6, 0x34, 0xf5,
	0x07, 0xe8, 0x85, 0x5c, 0xea, 0x4c, 0x78, 0x6f, 0xa2, 0x89, 0xf4, 0x61, 0xdd, 0x20, 0x95, 0x3d,
	0x24, 0x9f, 0x48, 0xcc, 0xd9, 0x15, 0xf5, 0x08, 0x9d, 0xce, 0x67, 0xbf, 0xc5, 0xf8, 0x1d, 0xb6,
	0xb1, 0x01, 0xce, 0xa2, 0xaf, 0x5e, 0x45, 0xfb, 0x5c, 0xec, 0x77, 0x15, 0x74, 0x7c, 0xb5, 0x7f,
	0x9a, 0x44, 0xa4, 0x81, 0xa7, 0x7a, 0x95, 0x14, 0x4f, 0x5e, 0xf9, 0xd9, 0x26, 0xaf, 0xf2, 0x2c,
	0x93, 0x77, 0xe0, 0xa9, 0x27, 0xaf, 0xfa, 0xd4, 0x93, 0x37, 0xf6, 0x0c, 0x93, 0x37, 0xbe, 0xb7,
	0xc9, 0x4b, 0xf9, 0xfb, 0xa4, 0x82, 0x4e, 0x0c, 0xe1, 0xef, 0xff, 0xb7, 0xe1, 0xff, 0xf6, 0x36,
	0x4c, 0x39, 0xf9, 0xc8, 0x40, 0xe4, 0x41, 0xe0, 0x50, 0x99, 0x5b, 0x8e, 0xd2, 0x95, 0xf6, 0xa9,
	0xe6, 0xea, 0x89, 0xad, 0xb8, 0xbc, 0xfb, 0x56, 0x9c, 0x36, 0xb2, 0x81, 0xbe, 0xb1, 0x4b, 0x1f,
	0xfb, 0x77, 0x21, 0xb6, 0x7e, 0x79, 0x0c, 0x1d, 0x4e, 0x5c, 0x57, 0x81, 0x6f, 0xb9, 0x36, 0xe0,
	0x5f, 0x54, 0xd0, 0x4b, 0x43, 0x76, 0x45, 0x3c, 0x9d, 0x55, 0xd8, 0x7d, 0x93, 0x35, 0xcf, 0xed,
	0xc1, 0x53, 0x1f, 0x64, 0xea, 0xb3, 0xf2, 0x4e, 0xfb, 0x2b, 0x23, 0xf7, 0xc5, 0xe8, 0xd4, 0x2a,
	0x48, 0x92, 0x84, 0x13, 0xbd, 0x7a, 0x12, 0xc6, 0x89, 0xa3, 0x13, 0x58, 0xe6, 0x49, 0xe5, 0x30,
	0xf0, 0x3c, 0x0d, 0x59, 0xb2, 0x51, 0xa5, 0xd5, 0x6c, 0xe2, 0x0f, 0xd0, 0xc9, 0xb8, 0x1d, 0x02,
	0x1f, 0x82, 0x1d, 0x4a, 0x70, 0x88, 0x08, 0x6d, 0x1b, 0x84, 0x58, 0x0f, 0x3d, 0xaf, 0x67, 0xe1,
	0x39, 0xf4, 0x86, 0xf9, 0xfa, 0xe9, 0x86, 0x03, 0xeb, 0xae, 0xef, 0xea, 0xaf, 0xab, 0x49, 0x92,
	0x11, 0x5d, 0x8b, 0xa5, 0x8b, 0xa8, 0x72, 0xb9, 0x79, 0x19, 0xcf, 0xa0, 0xe9, 0x15, 0x90, 0x21,
	0xf7, 0xc1, 0x21, 0xdb, 0x9b, 0xe0, 0x13, 0xb9, 0x09, 0x84, 0x83, 0x60, 0x21, 0xb7, 0x81, 0xb8,
	0x82, 0xf8, 0x4c, 0x92, 0x75, 0x16, 0xfa, 0x8e, 0xb5, 0x76, 0x14, 0x3d, 0x8f, 0xc6, 0xee, 0xb5,
	0x43, 0xb9, 0xd9, 0xc2, 0xe3, 0xa8, 0xba, 0xcd, 0x5d, 0x09, 0x3f, 0xf9, 0xd3, 0xdf, 0x7f, 0x5a,
	0x9e, 0x99, 0x33, 0x66, 0xcc, 0x57, 0xd5, 0xb7, 0xf4, 0x2e, 0xf5, 0xe9, 0x06, 0x74, 0xc1, 0x97,
	0x69, 0x27, 0xa2, 0xf1, 0xc3, 0x4c, 0x71, 0x3f, 0x7a, 0x5c, 0x2e, 0x7d, 0x5c, 0x8e, 0x18, 0xc5,
	0x8f, 0x2b, 0xe8, 0x58, 0xe1, 0x46, 0x85, 0xcf, 0x64, 0xe8, 0xef, 0xb6, 0xc8, 0x99, 0x67, 0x47,
	0xfa, 0xc5, 0x1c, 0xfd, 0xac, 0xbc, 0xd3, 0xfe, 0x43, 0x9e, 0xa3, 0x97, 0x6e, 0xe7, 0x39, 0x52,
	0xc3, 0x44, 0x3c, 0x57, 0x48, 0x61, 0xb6, 0x34, 0x1a, 0x82, 0xd0, 0xe8, 0x01, 0x09, 0x03, 0x22,
	0x19, 0x69, 0x35, 0x07, 0x9c, 0x55, 0x7e, 0xe2, 0x50, 0x49, 0xad, 0xa5, 0xef, 0x6a, 0xbe, 0x1e,
	0x8e, 0xe4, 0xeb, 0x0a, 0x7a, 0xcd, 0xbc, 0x54, 0xcc, 0xd7, 0xae, 0xfd, 0xaf, 0x61, 0x74, 0x24,
	0x45, 0x7e, 0x0c, 0x1d, 0xe0, 0x40, 0x9d, 0x08, 0xf8, 0x37, 0xf1, 0xdc, 0x9e, 0x50, 0xcf, 0x7e,
	0x3d, 0x51, 0xdd, 0xcf, 0xea, 0xee, 0x73, 0x54, 0xfc, 0xaa, 0x8c, 0x26, 0x73, 0x1d, 0xe0, 0xe3,
	0x85, 0xc0, 0x26, 0xb0, 0x9f, 0x18, 0x62, 0x8d, 0xc1, 0xfe, 0xab, 0xb1, 0xd3, 0xfe, 0x79, 0x1e,
	0xec, 0x83, 0x79, 0xb0, 0x4d, 0x92, 0x20, 0x9c, 0x22, 0xaa, 0x50, 0x24, 0x6b, 0x3d, 0xe2, 0xca,
	0xb3, 0x82, 0x2c, 0x2e, 0x2c, 0xbd, 0xab, 0xf1, 0xbc, 0x37, 0x12, 0xcf, 0x59, 0x74, 0xde, 0x3c,
	0x37, 0x12, 0xcf, 0x91, 0x28, 0x9e, 0xc5, 0x5f, 0x5b, 0xbb, 0xbf, 0x2e, 0xa3, 0x83, 0xf9, 0x6d,
	0x09, 0xbf, 0x38, 0xf0, 0xad, 0xfa, 0x66, 0x37, 0x90, 0x3d, 0xf3, 0x64, 0x21, 0x56, 0x99, 0x32,
	0xff, 0x61, 0xec, 0xb4, 0x3f, 0xcf, 0x83, 0x75, 0x28, 0x0f, 0x96, 0x30, 0x2f, 0xa5, 0x7a, 0xf4,
	0xbc, 0xec, 0xb1, 0x86, 0x6c, 0x40, 0x9b, 0x89, 0x20, 0xdf, 0xd3, 0x00, 0x2e, 0x8f, 0x04, 0xd0,
	0x42, 0x17, 0xcc, 0x99, 0x91, 0x00, 0x8e, 0xd6, 0xa1, 0x89, 0xeb, 0xc3, 0x10, 0xd4, 0xa0, 0x35,
	0x4b, 0xf8, 0x93, 0x0a, 0x7a, 0x65, 0x97, 0x05, 0x73, 0x28, 0x82, 0xb3, 0xc5, 0x08, 0x0e, 0xd9,
	0x4f, 0xa7, 0x3e, 0x2d, 0xef, 0xb4, 0xff, 0x9d, 0x07, 0x94, 0xf4, 0x01, 0x4a, 0xd6, 0x19, 0x27,
	0x5e, 0x14, 0x48, 0x5c, 0x9f, 0x84, 0x02, 0xb8, 0x79, 0xab, 0x18, 0xe3, 0x41, 0xcf, 0x11, 0xb0,
	0xaf, 0x6b, 0xd8, 0x3b, 0x23, 0x61, 0xbf, 0x8e, 0xae, 0x99, 0x57, 0x47, 0xc3, 0x3e, 0xe4, 0x88,
	0x43, 0x59, 0x98, 0xc6, 0x67, 0x9e, 0x60, 0x41, 0x35, 0x2d, 0x1a, 0xf1, 0x77, 0x9e, 0x02, 0x4e,
	0x3e, 0xad, 0xa0, 0x63, 0x85, 0x6b, 0x5c, 0xfe, 0x0a, 0xde, 0x6d, 0x4f, 0xcf, 0x5f, 0xc1, 0xbb,
	0xee, 0x83, 0x53, 0xbf, 0x2d, 0xef, 0xb4, 0xbf, 0xcc, 0xf3, 0xf2, 0xf2, 0x6a, 0xc1, 0x15, 0xac,
	0xee, 0x25, 0xcb, 0x1c, 0x6e, 0xda, 0x97, 0xbb, 0x76, 0xd7, 0x46, 0xf7, 0xf5, 0xc5, 0xf8, 0x96,
	0x7a, 0x31, 0xee, 0xcf, 0x15, 0xfd, 0x79, 0x05, 0xbd, 0x3c, 0x74, 0xab, 0xc2, 0x33, 0x19, 0x0d,
	0xa3, 0x56, 0x40, 0xf3, 0xfc, 0x9e, 0x7c, 0x63, 0xda, 0x7e, 0xff, 0xe4, 0x38, 0x99, 0x7d, 0xdc,
	0x24, 0xfb, 0x1f, 0x09, 0xb9, 0x67, 0x99, 0xbb, 0xd8, 0x96, 0x1c, 0x4d, 0xdc, 0x77, 0x46, 0x12,
	0x77, 0x0d, 0x5d, 0x35, 0xaf, 0x14, 0x13, 0x37, 0xb2, 0xdd, 0x7d, 0x25, 0xef, 0x6d, 0x45, 0xde,
	0xb5, 0xaf, 0x49, 0x5e, 0x7e, 0x21, 0xce, 0xd8, 0x33, 0x2b, 0x8f, 0xcb, 0xa5, 0x1b, 0x7f, 0xa9,
	0xee, 0xb4, 0x3f, 0xab, 0xa2, 0x4a, 0xcb, 0x6a, 0xe2, 0x3b, 0xa8, 0x36, 0x4f, 0xb9, 0x43, 0xda,
	0xcb, 0x8b, 0xf8, 0x6a, 0xfc, 0x63, 0xbd, 0x20, 0xfa, 0x27, 0x57, 0x42, 0x7d, 0x87, 0xa8, 0xa9,
	0x26, 0x2c, 0x00, 0xae, 0xff, 0xef, 0x81, 0x30, 0x7d, 0x08, 0x5b, 0x05, 0x25, 0x27, 0xb1, 0x5a,
	0xd5, 0x8b, 0x56, 0xd3, 0x6a, 0xce, 0x18, 0xe5, 0xd6, 0x11, 0x1a, 0x04, 0x9e, 0x6b, 0x47, 0xde,
	0x8d, 0xef, 0x09, 0xe6, 0xcf, 0x0d, 0x3c, 0x59, 0xe9, 0x28, 0x74, 0x9a, 0xf8, 0xdb, 0xe8, 0xdd,
	0x22, 0x74, 0x34, 0x2b, 0x6b, 0xcc, 0xe9, 0x29, 0x84, 0xba, 0xd4, 0x5b, 0x67, 0xbc, 0x4b, 0xa5,
	0x62, 0x48, 0x6d, 0xa9, 0x0c, 0x34, 0x6c, 0x5d, 0x2a, 0xed, 0xcd, 0x28, 0x04, 0x3e, 0x0c, 0xc0,
	0x56, 0xe6, 0x38, 0xd6, 0x5a, 0xb9, 0xa3, 0x0a, 0x5c, 0xc4, 0x37, 0xd1, 0xfc, 0xf0, 0x02, 0x69,
	0x22, 0x9b, 0xf9, 0x92, 0xba, 0xbe, 0x88, 0xac, 0xea, 0xa6, 0x3a, 0x1b, 0x01, 0xe0, 0x80, 0x2f,
	0x5d, 0xea, 0x09, 0x6b, 0x65, 0x59, 0x65, 0xbb, 0x84, 0x17, 0xd1, 0xed, 0xc1, 0x6c, 0xfa, 0x3a,
	0x4e, 0x52, 0x6d, 0xd2, 0x2d, 0x20, 0x01, 0xf0, 0xae, 0x2b, 0x84, 0xab, 0x90, 0x62, 0x84, 0x46,
	0x9a, 0xea, 0x23, 0xde, 0x5a, 0xb9, 0x85, 0x2a, 0xaf, 0x35, 0x9b, 0xf8, 0x2d, 0x74, 0xbd, 0x3f,
	0x23, 0xf5, 0x49, 0xe8, 0xa7, 0xc7, 0x01, 0xce, 0x19, 0x27, 0xcc, 0xb6, 0x43, 0xae, 0xce, 0xae,
	0x0b, 0x0a, 0xe0, 0x5b, 0xc0, 0x89, 0x70, 0x1d, 0xb0, 0xde, 0xff, 0x97, 0x81, 0xfe, 0x69, 0xa4,
	0xaa, 0xf9, 0x9b, 0x51, 0xab, 0xe0, 0x8f, 0x8c, 0x76, 0x5c, 0x91, 0x11, 0xc9, 0xa9, 0x2f, 0xa8,
	0xad, 0x89, 0x4b, 0xaa, 0x0b, 0x85, 0x2a, 0x07, 0x21, 0xb9, 0x1b, 0x55, 0x51, 0x3d, 0x86, 0x72,
	0x53, 0x9d, 0xd6, 0xa6, 0xea, 0x41, 0x74, 0x59, 0x5b, 0xe4, 0xfe, 0x26, 0xe4, 0x0d, 0xea, 0x38,
	0x01, 0x67, 0x51, 0xea, 0x75, 0xe6, 0x79, 0x6c, 0x5b, 0x1f, 0x4a, 0x95, 0x66, 0xdc, 0xfd, 0x81,
	0xf6, 0x98, 0x67, 0x0e, 0x90, 0x75, 0x8f, 0x6d, 0x5b, 0xd3, 0x07, 0x5a, 0x35, 0xa5, 0x59, 0x95,
	0x62, 0x6e, 0x42, 0x7d, 0x92, 0xec, 0x11, 0xf8, 0x37, 0xe6, 0x90, 0xa9, 0x5f, 0x15, 0x18, 0xdf,
	0xe6, 0xd4, 0x97, 0x42, 0x2b, 0x4c, 0xc3, 0x84, 0x8e, 0xc7, 0xc2, 0xc7, 0x47, 0x63, 0x63, 0xf4,
	0xaf, 0xd8, 0xfa, 0x8e, 0xb1, 0x5c, 0x7a, 0x3f, 0xfd, 0xf6, 0xf5, 0x63, 0xa3, 0xf4, 0xd8, 0x28,
	0x7d, 0x6c, 0x94, 0x7e, 0x63, 0x94, 0xfe, 0x6c, 0x94, 0xbe, 0x32, 0x4a, 0x7f, 0x2c, 0x97, 0xd6,
	0xc6, 0xa2, 0xb7, 0xf6, 0xa5, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x94, 0x81, 0x26, 0x1a, 0xc8,
	0x1b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ConsumerServiceClient is the client API for ConsumerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConsumerServiceClient interface {
	// EnableOrDisableConsumer
	EnableOrDisableConsumer(ctx context.Context, in *EnableOrDisableConsumerRequest, opts ...grpc.CallOption) (*EnableOrDisableConsumerResponse, error)
	// GetConsumerCallLimits
	GetConsumerCallLimits(ctx context.Context, in *GetConsumerCallLimitsRequest, opts ...grpc.CallOption) (*GetConsumerCallLimitsResponse, error)
	// GetConsumer
	GetConsumer(ctx context.Context, in *GetConsumerRequest, opts ...grpc.CallOption) (*GetConsumerResponse, error)
	// GetConsumers
	GetConsumers(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetConsumersResponse, error)
	// GetConsumers
	GetConsumersForLoggedInUser(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetConsumersForLoggedInUserResponse, error)
	// SetConsumerCallsLimit
	SetConsumerCallsLimit(ctx context.Context, in *SetConsumerCallsLimitRequest, opts ...grpc.CallOption) (*SetConsumerCallsLimitResponse, error)
	// UpdateConsumerRedirectURL
	UpdateConsumerRedirectURL(ctx context.Context, in *UpdateConsumerRedirectURLRequest, opts ...grpc.CallOption) (*UpdateConsumerRedirectURLResponse, error)
}

type consumerServiceClient struct {
	cc *grpc.ClientConn
}

func NewConsumerServiceClient(cc *grpc.ClientConn) ConsumerServiceClient {
	return &consumerServiceClient{cc}
}

func (c *consumerServiceClient) EnableOrDisableConsumer(ctx context.Context, in *EnableOrDisableConsumerRequest, opts ...grpc.CallOption) (*EnableOrDisableConsumerResponse, error) {
	out := new(EnableOrDisableConsumerResponse)
	err := c.cc.Invoke(ctx, "/consumer.ConsumerService/EnableOrDisableConsumer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consumerServiceClient) GetConsumerCallLimits(ctx context.Context, in *GetConsumerCallLimitsRequest, opts ...grpc.CallOption) (*GetConsumerCallLimitsResponse, error) {
	out := new(GetConsumerCallLimitsResponse)
	err := c.cc.Invoke(ctx, "/consumer.ConsumerService/GetConsumerCallLimits", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consumerServiceClient) GetConsumer(ctx context.Context, in *GetConsumerRequest, opts ...grpc.CallOption) (*GetConsumerResponse, error) {
	out := new(GetConsumerResponse)
	err := c.cc.Invoke(ctx, "/consumer.ConsumerService/GetConsumer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consumerServiceClient) GetConsumers(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetConsumersResponse, error) {
	out := new(GetConsumersResponse)
	err := c.cc.Invoke(ctx, "/consumer.ConsumerService/GetConsumers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consumerServiceClient) GetConsumersForLoggedInUser(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetConsumersForLoggedInUserResponse, error) {
	out := new(GetConsumersForLoggedInUserResponse)
	err := c.cc.Invoke(ctx, "/consumer.ConsumerService/GetConsumersForLoggedInUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consumerServiceClient) SetConsumerCallsLimit(ctx context.Context, in *SetConsumerCallsLimitRequest, opts ...grpc.CallOption) (*SetConsumerCallsLimitResponse, error) {
	out := new(SetConsumerCallsLimitResponse)
	err := c.cc.Invoke(ctx, "/consumer.ConsumerService/SetConsumerCallsLimit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consumerServiceClient) UpdateConsumerRedirectURL(ctx context.Context, in *UpdateConsumerRedirectURLRequest, opts ...grpc.CallOption) (*UpdateConsumerRedirectURLResponse, error) {
	out := new(UpdateConsumerRedirectURLResponse)
	err := c.cc.Invoke(ctx, "/consumer.ConsumerService/UpdateConsumerRedirectURL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConsumerServiceServer is the server API for ConsumerService service.
type ConsumerServiceServer interface {
	// EnableOrDisableConsumer
	EnableOrDisableConsumer(context.Context, *EnableOrDisableConsumerRequest) (*EnableOrDisableConsumerResponse, error)
	// GetConsumerCallLimits
	GetConsumerCallLimits(context.Context, *GetConsumerCallLimitsRequest) (*GetConsumerCallLimitsResponse, error)
	// GetConsumer
	GetConsumer(context.Context, *GetConsumerRequest) (*GetConsumerResponse, error)
	// GetConsumers
	GetConsumers(context.Context, *empty.Empty) (*GetConsumersResponse, error)
	// GetConsumers
	GetConsumersForLoggedInUser(context.Context, *empty.Empty) (*GetConsumersForLoggedInUserResponse, error)
	// SetConsumerCallsLimit
	SetConsumerCallsLimit(context.Context, *SetConsumerCallsLimitRequest) (*SetConsumerCallsLimitResponse, error)
	// UpdateConsumerRedirectURL
	UpdateConsumerRedirectURL(context.Context, *UpdateConsumerRedirectURLRequest) (*UpdateConsumerRedirectURLResponse, error)
}

// UnimplementedConsumerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedConsumerServiceServer struct {
}

func (*UnimplementedConsumerServiceServer) EnableOrDisableConsumer(ctx context.Context, req *EnableOrDisableConsumerRequest) (*EnableOrDisableConsumerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnableOrDisableConsumer not implemented")
}
func (*UnimplementedConsumerServiceServer) GetConsumerCallLimits(ctx context.Context, req *GetConsumerCallLimitsRequest) (*GetConsumerCallLimitsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConsumerCallLimits not implemented")
}
func (*UnimplementedConsumerServiceServer) GetConsumer(ctx context.Context, req *GetConsumerRequest) (*GetConsumerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConsumer not implemented")
}
func (*UnimplementedConsumerServiceServer) GetConsumers(ctx context.Context, req *empty.Empty) (*GetConsumersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConsumers not implemented")
}
func (*UnimplementedConsumerServiceServer) GetConsumersForLoggedInUser(ctx context.Context, req *empty.Empty) (*GetConsumersForLoggedInUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConsumersForLoggedInUser not implemented")
}
func (*UnimplementedConsumerServiceServer) SetConsumerCallsLimit(ctx context.Context, req *SetConsumerCallsLimitRequest) (*SetConsumerCallsLimitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetConsumerCallsLimit not implemented")
}
func (*UnimplementedConsumerServiceServer) UpdateConsumerRedirectURL(ctx context.Context, req *UpdateConsumerRedirectURLRequest) (*UpdateConsumerRedirectURLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateConsumerRedirectURL not implemented")
}

func RegisterConsumerServiceServer(s *grpc.Server, srv ConsumerServiceServer) {
	s.RegisterService(&_ConsumerService_serviceDesc, srv)
}

func _ConsumerService_EnableOrDisableConsumer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableOrDisableConsumerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsumerServiceServer).EnableOrDisableConsumer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/consumer.ConsumerService/EnableOrDisableConsumer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsumerServiceServer).EnableOrDisableConsumer(ctx, req.(*EnableOrDisableConsumerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsumerService_GetConsumerCallLimits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConsumerCallLimitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsumerServiceServer).GetConsumerCallLimits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/consumer.ConsumerService/GetConsumerCallLimits",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsumerServiceServer).GetConsumerCallLimits(ctx, req.(*GetConsumerCallLimitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsumerService_GetConsumer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConsumerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsumerServiceServer).GetConsumer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/consumer.ConsumerService/GetConsumer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsumerServiceServer).GetConsumer(ctx, req.(*GetConsumerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsumerService_GetConsumers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsumerServiceServer).GetConsumers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/consumer.ConsumerService/GetConsumers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsumerServiceServer).GetConsumers(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsumerService_GetConsumersForLoggedInUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsumerServiceServer).GetConsumersForLoggedInUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/consumer.ConsumerService/GetConsumersForLoggedInUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsumerServiceServer).GetConsumersForLoggedInUser(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsumerService_SetConsumerCallsLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetConsumerCallsLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsumerServiceServer).SetConsumerCallsLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/consumer.ConsumerService/SetConsumerCallsLimit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsumerServiceServer).SetConsumerCallsLimit(ctx, req.(*SetConsumerCallsLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsumerService_UpdateConsumerRedirectURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConsumerRedirectURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsumerServiceServer).UpdateConsumerRedirectURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/consumer.ConsumerService/UpdateConsumerRedirectURL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsumerServiceServer).UpdateConsumerRedirectURL(ctx, req.(*UpdateConsumerRedirectURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ConsumerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "consumer.ConsumerService",
	HandlerType: (*ConsumerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnableOrDisableConsumer",
			Handler:    _ConsumerService_EnableOrDisableConsumer_Handler,
		},
		{
			MethodName: "GetConsumerCallLimits",
			Handler:    _ConsumerService_GetConsumerCallLimits_Handler,
		},
		{
			MethodName: "GetConsumer",
			Handler:    _ConsumerService_GetConsumer_Handler,
		},
		{
			MethodName: "GetConsumers",
			Handler:    _ConsumerService_GetConsumers_Handler,
		},
		{
			MethodName: "GetConsumersForLoggedInUser",
			Handler:    _ConsumerService_GetConsumersForLoggedInUser_Handler,
		},
		{
			MethodName: "SetConsumerCallsLimit",
			Handler:    _ConsumerService_SetConsumerCallsLimit_Handler,
		},
		{
			MethodName: "UpdateConsumerRedirectURL",
			Handler:    _ConsumerService_UpdateConsumerRedirectURL_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/openbank/openbank/v1/consumer/all.proto",
}
